### PR TITLE
Docker install

### PR DESCRIPTION
**Pull request by oncletom**
Some undergoing work to only pull stuff from the cloud/NSA tap surveillance network to analyse the network:
- env variables over configuration files for some touchy points (easier to provision from a CLI)
- each service is more isolated
- each service carries only its required dependencies
- each service is easier to upgrade because they don't rely on a global stack, possibly conflictual
- each service install is now documented in a way you can guarantee it will work
- Docker compose to orchestrate services altogether

```bash
docker-compose up
```

And we are done.

### CODE REVIEW

**Comment by oncletom** [comment]
hyphe-docker

So I get to a stage where the entire stack can be built from per-service `Dockerfile`.
The only missing bit so far is the communication with the crawler/scrapy container.

For some reason, the `bin/deploy_scrapy_spider.sh` does not work as expected, because of the `crawler/deploy.py` file and specifically `from hyphe_backend.lib import config_hci`.
Python does not recognise the path so the rest of the script is not executed — and then the `egg` is not published onto the crawler service. And I am not a Python guy so it takes me ages to understand why the import path is not resolved properly (I assume it uses the `__init__.py` files but I don't understand why it fails in this case).

You can also see on the gif that further communications with the crawler fail. So probably I am missing some config alteration to enforce it uses the `HYPHE_CRAWLER_HOST` env variable instead of localhost.

Any feedback is welcome :-)

**Comment by boogheta** [comment]
All right so here are a few points in addition to the comments along the code in the commits:
- at least for now, I don't think we want to switch the main hyphe install to docker, proposing it as extra would be great especially to have it installable on Mac OS, but the kernel 3.10 requirement makes it unacceptable for a lot of older distributions on which rely still the majority of servers in research universities. So we would like to be able to keep the current way of installing and provide a docker package as extra. Because of this, some of your changes won't be pullable as they would break the regular install (for instance https://github.com/oncletom/hyphe/commit/362912c5a1024b364da7dee63ec0f23e22a53008). I would really love if you could instead have a Docker directory in which a script would build the docker package from the parent directory instead of actually modifying the whole source, or a build docker script in bin that would build the whole thing in a build/dist/docker directory. Commenting the whole copying of the config in deploy (https://github.com/oncletom/hyphe/commit/d391016656efb83cce8d9eab2a4516a68ec1db12#diff-f9ceb2ad29cd25074d0ca330a6a14e8eR19) is not possible for the same reasons.
- I like the service isolation for the daemon dependencies especially (scrapyd and mongo), sounds like the way to go 
- env variables vs conf : we use multiple instances of Hyphe on a same server, I feel like using env variables is so very secure for future uses outside docker. I'd rather like trying to find a way of fixing the path thingy than migrating to those. If that's really the only way, I like how you me it a fallback in the code, it's definitely the good option so that compat keeps ensured.
- virtualenv : I believe your path issue mainly comes from this. In the regular install we declare the root directory of hyphe as a "path" for the virtualenv's python, so it has access from its lib from elsewhere when ran within the virtualenv. Your alternative might be to declare a global env variable PYTHONPATH that would include hyphe's directory path

**Comment by oncletom** [comment]
Thanks a lot for your inputs @boogheta, I have amended the commits and ensured a backward compatibility with all the Python files. The only changes are related to env variables ([why env variables?](http://12factor.net/config)) which defaults to the config file.

I can connect to the UI and start a crawl. Although the last trouble I face is displayed in the crawler logs:

```
crawler_1  | 2015-06-09 18:03:38+0000 [-] Process started:  project='hyphe.test' spider='pages' job='d926c8de0ed111e5a1690242ac110134' pid=19 log='/var/log/scrapyd/hyphe.test/pages/d926c8de0ed111e5a1690242ac110134.log' items='file:///var/lib/scrapyd/items/hyphe.test/pages/d926c8de0ed111e5a1690242ac110134.jl'
crawler_1  | 2015-06-09 18:03:40+0000 [Launcher,19/stderr] /usr/local/lib/python2.7/dist-packages/scrapy/link.py:16: UserWarning: Do not instantiate Link objects with unicode urls. Assuming utf-8 encoding (which could be wrong)
crawler_1  | 	  warnings.warn("Do not instantiate Link objects with unicode urls. " \
```

This is somewhat related to scrapyd but even though I install the version which fixes it (`0.24`), the error still happens. It seems to have some impact on the crawling as nothing else happens (the *page crawled* counter does not increment).

**Comment by boogheta** [comment]
Looks great!
I believe I've seen the warning before, this is probably something that needs to be fixed in hyphe but shouldn't have any impact, since all urls being indeed unicode from utf8.
Did your crawl finish and get indexed properly (do you have discovered webentities)?
If such I believe we're nearly good to go, thanks a lot again for your work!

**Comment by oncletom** [comment]
@boogheta :-)

Well the crawl did not go further than that. Pages have not been harvested and I have not noticed any error. I will retry from scratch this morning, just in case. I will try again with one Web entity, 1 click depth and will wait.

Is there anything specific to do/configure to go to the next step?

**Comment by boogheta** [comment]
arf :/
Can you check whether scrapyd succeeded in storing anything within MongoDB?
You can do it with something like:
```bash
mongo hyphe --eval "db.test.pages.count()"
mongo hyphe --eval "db.test.queue.count()"
mongo hyphe --eval "db.test.jobs.forEach(printjson)"
```

If it works I guess what could be good to conclude would be to reassemble only the good commits maybe in a new PR and add a point to the Install documentation about docker

**Comment by oncletom** [comment]
@boogheta here is the output of the commands:

```
root@de161d7f7f8b:/# mongo hyphe --eval "db.test.pages.count()"
MongoDB shell version: 3.0.3
connecting to: hyphe
0
root@de161d7f7f8b:/# mongo hyphe --eval "db.test.queue.count()"
MongoDB shell version: 3.0.3
connecting to: hyphe
0
root@de161d7f7f8b:/# mongo hyphe --eval "db.test.jobs.forEach(printjson)"
MongoDB shell version: 3.0.3
connecting to: hyphe
2015-06-10T10:44:09.843+0000 E QUERY    TypeError: Property 'forEach' of object hyphe.test.jobs is not a function
    at (shell eval):1:14
```

Furthermore:

```
$ mongo
> show dbs
hyphe  0.078GB
local  0.078GB
> use hyphe
switched to db hyphe
> show collections
corpus
system.indexes
test.jobs
test.logs
test.pages
test.queries
test.queue
test.stats
> db.test.pages.find()
```

Nothing is stored in pages apparently. Maybe the Mongodb connection is failing within the egg.

EDIT: that's it. I unzipped the uploaded egg and the MONGO_HOST value is set to localhost:

```bash
MONGO_HOST = 'localhost'
MONGO_PORT = 27017
MONGO_DB = 'hyphe'
MONGO_QUEUE_COL = 'test.queue'
MONGO_PAGESTORE_COL = 'test.pages'
```

Are the settings of `PHANTOM` used? Because it is set to the following:

```json
PHANTOM = {
  "PATH": os.path.join('/app', 'bin', 'hyphe-phantomjs-2.0.0'),
  "JS_PATH": os.path.join('/app', 'hyphe_backend', 'crawler', BOT_NAME, 'spiders', 'js'),
  "TIMEOUT": 600,
  "IDLE_TIMEOUT": 20,
  "AJAX_TIMEOUT": 15
}
```

And they will definitely fail as the crawler is deployed in a separate container.

**Comment by oncletom** [comment]
screen shot 2015-06-10 at 12 13 27

:tada:

**Comment by oncletom** [comment]
I have added some instructions and reorganised/merged commits to make the history to feel slicker.

**Comment by boogheta** [comment]
Yeahhhh!
And thanks a lot for the doc!

So if I understand correctly, there was still one mongodb host setting missing for the crawler and that was it?

PS: I'm at a conference until tomorrow afternoon, so I'll wait until then to merge more comfortably.

**Comment by oncletom** [comment]
:+1: 

Yep, the `config["mongo-scrapy"]["host"]` refers to a host but depending on *where* this variable is used, it either refers to the *mongodb host* or the *scrapyd host*. Although there was no error reported by the egg sent to the crawler about its inability to connect to mongodb.

The fix is [located here](https://github.com/oncletom/hyphe/commit/e8bc2a7b77ce97489ba69ef5c5da638c8cff3381#diff-f9ceb2ad29cd25074d0ca330a6a14e8eR67).

Take some time to follow the instructions, and feel free to use Vagrant to start this in an Ubuntu VM.

**Comment by oncletom** [comment]
And I added a Vagrantfile. If you have It installed + Virtualbox, simply cd in the repository and type `vagrant up`. It will build everything from scratch, including a pristine VM.

**Comment by boogheta** [comment]
Well spotted about the mongo-scrapy host! it's an old heritage thing I should probably clean up now.

Will try with ubuntu and macos asap

**Comment by diegoantolinosbasso** [comment]
Hi @oncletom,
We just tried installing hyphe on a mac with @boogheta and succeeded !

Just a small thing : we had to manually set the boot2docker environment variables to have boot2docker and docker-compose talk to each others.
Also, the port is 8000, not 6800 : open http://$(boot2docker ip):8000
Anyway, don't bother, we'll fix it !
Thx

**Comment by boogheta** [comment]
Hey, a few more Docker questions following this tryout:
- if i understand correctly, docker builds a big archive that assembles all the containers, including the data directories (everything that is stored in mongo, the lucene-data, etc). Currently this archive with no crawls is about 5Go, and our knowledge of hyphe's use is we can easily reach up to 15-20Go for a big corpus, which means the file will keep growing up. Do you know if there would be a way to externalize parts of it, like split the lucene data in one partition for instance. And also could one possibly clean up like big logs that get stacked by scrapyd?
- if someone wants to update the code (by pulling new commits for instance, or to dev/debug), how can he ensure the modifications are included in the docker build? Do we need to do a `docker-compose build` before `docker-compose up`
- can we build some kind of archive that we could publish on the web for people who could just run some released build without having to go through the 15 minutes install, and how can it be ran afterwards?

Also, no problem to me with this, but I noticed some of the docker containers built are referring to debian weezer while others refer to debian jessie, is this intentional and why?

PS: Again, so many thanks for investigating this, this is a real game-changer for local installs!

**Comment by oncletom** [comment]
Hey :-)

thanks for having taken the time to investigate the proposal.

`docker-compose` is just a helper to orchestrate Docker image creation and how they are created and connected. The actual setup shapes an image per important service, so **5 Docker images**. One of them (Mongo) is directly pulled from the public Docker hub (https://hub.docker.com/).

The hyphe specific images have to be built by users at the moment — and this is something which can be automated if you sign up on Docker Hub, create an organisation (i.e: medialab) and then create *Automated builds*. Therefore, every commit pushed to the master branch of hyphe on GitHub will trigger a Docker image build. 
Ideally people would retrieve them by doing `docker pull medialab/hyphe-frontend` etc. Build once, run multiple run, everywhere* :-)

The `docker-compose.yml` could then be heavily simplified to rely on these automated images (instead of the `build` key). And you to keep a `docker-compose.dev.yml` to automate the build on the dev, for instance.

Speaking of the Docker images, they are not optimised: as you rightly point out, they use different base images. Ideally we would like them to share a maximum amount of layers to reduce the disk space consumption. What matters is that logic becomes isolated inside the Docker image and has no impact on the end user.

Also, I mentioned *boot2docker* rather than OSX specifically because it means it also works for Windows users as well :-) (cf https://docs.docker.com/installation/windows/) They can install it to get docker instructions ran from the boot2docker Linux VM.



* almost

**Comment by boogheta** [comment]
Hey @oncletom, just a quick message to let you know you were precursor and led us in the end to choose Docker as the regular installation process for the future. We made it more generic and configurable and it works on all OS now!
Thanks again for your help!

**Pull request merged**
